### ISSUE TITLE
Only pulls the first 30 repos

### ISSUE THREAD

**Issue by jescalan** [edgarjs/alfred-github-repos#1]
It appears as if this script only pulls the first 30 repos for each user/organization. I'm going to look into making a pull request to patch this, just a heads up! I love how quick and responsive this is, but the 20 repo limitation is a killer for me.

It's probably because of this limitation, which we could just boost to an enormous number to solve the problem: https://developer.github.com/v3/#pagination

**Comment by grobmeier** [comment]
I am also suffering from this limitation. I am working with multiple organizations, can't see all of my personal ones. Would love if this would be merged.
