### ISSUE TITLE
.auth_token file should be encripted

### ISSUE THREAD

**Issue by caipivara** [edgarjs/alfred-github-repos#10]
The plugin saves the user plain token, this is so insecure and even more if you do backups...

**Comment by edgarjs** [comment]
Ideally you'd generate a token specific for this workflow. Credentials are now stored in your home directory, and you can revoke token at any time.

**Comment by benwoodward** [comment]
I'm not a fan of auth tokens being stored on my machine in plaintext. Maybe the solution is the check whether an specific ENV var is set, e.g. `GITHUB_REPOS_TOKEN` and if not fallback to using config file.
