### ISSUE TITLE
Support fetching repos with pagination

### ISSUE THREAD

**Issue by danielgalasko** [edgarjs/alfred-github-repos#11]
Hi, Great package by the way! Just wanted to say that I just encountered an issue with updating the cache and noticed some of my repos were missing. On closer inspection it turns out that `get_org_repos` does not actually use pagination:

```ruby
def get_org_repos(org)
    res = get "/orgs/#{org}/repos"
    if res.is_a?(Array)
      res.map do |repo|
        { 'name' => repo['full_name'], 'url' => repo['html_url'] }
      end
    else # TODO: handle error
      []
    end
  end
```

I went ahead and modified it to use `res = get "/orgs/#{org}/repos?per_page=100"` just to see and lo and behold my repos popped in.

Don't mind submitting a PR but not entirely sure how I could achieve this in ruby?

**Comment by edgarjs** [comment]
Pagination should be working, it is handled here: https://github.com/edgarjs/alfred-github-repos/blob/master/github#L167

**Comment by danielgalasko** [comment]
Ah I see, interesting, wonder why when I change it to `per_page=100` that fetches my repos. Are you sure this is actually what GitHub supports today on the repos endpoint? Cant understand why this doesn't work then for me if you saying it should...

**Comment by edgarjs** [comment]
If you see line 144 it already has the `per_page` parameter. This was aded in a PR, honestly I've lost track of the github API recently so I'm afraid I can't assure that is how github works. But the pagination works for me :)
