### ISSUE TITLE
Version 2.0 no longer makes it easy to search user and org repos

### ISSUE THREAD

**Issue by jburnham** [edgarjs/alfred-github-repos#15]
Hi,

I've been using this workflow for years now and love it. Thank you for the effort in creating this. I recently decided to try to update when I saw today this version was added.

My main use of this workflow is to quickly open a GitHub repo that exists in my org. As there are many dozens of them, this flow has saved me lots of time by quickly opening the one I want because of the local cache the previous version of this workflow wrote. This allowed me to be able to do a kind of fuzzy search of my org repos to find the right one. Now, the 2.0 version includes search results from all of GitHub, making it much harder to find what I want unless I know the exact name.

Would it be possible to bring back the ability to search only my user/org repos and have a separate command to search public repos?

**Comment by edgarjs** [comment]
Hi. I thought the cache was useless so I removed it in this version. Thank you for sharing your use case. I'll add it back as soon as I have a bit of time. Or you can submit a pull request if you want to contribute and have it faster ;)
