### ISSUE TITLE
some suggestions.

### ISSUE THREAD

**Issue by neverrop** [edgarjs/alfred-github-repos#22]
Hi, thanks for the useful workflow.

I have two suggestions as following:
1. when type 'gh ' with no argv, is it better to show all repos?
2. I think it might be useful to have another 'ghs ' branch, for showing and searching our starred repos.

**Comment by edgarjs** [comment]
Thanks for the suggestions. There's a newer version in the cooks (already on master) that has the following features:

1. Search your own repos from cache with `repo <query>`
2. Search across Github with the command: `gh <query>` (not cached)
3. Search PRs you're involved in (cached)

Feel free to try it out and give any feedback before the official release.
