### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by mvdnbrk** [edgarjs/alfred-github-repos#23]
The `authenticate` command did not create the `~/.github-repos/config` file.
After creating it manually I could run the `authenticate` command and my credentials were stored in the config file.

**Comment by kylemh** [comment]
I'm unable to authenticate. It would open a new tab in my browser to generate a token, but wouldn't give me a spot to enter that same token.

**Comment by edgarjs** [comment]
After you generate your access token in github, run the command `gh-login your@email.com yourtoken`. That should create the file and leave you authenticated.
