### ISSUE TITLE
Github token Never use

### ISSUE THREAD

**Issue by pakerchang** [edgarjs/alfred-github-repos#26]
Hi, I'm having a bit of a problem.

The first time I logged in, I used a Github password instead of a token.
It shows my repos, but doesn't capture the latest ones.

When I try to login with my token again, it shows on Github that my token has never been used.

OSX 10.15.6
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by edgarjs** [comment]
@pakerchang check if the credentials file has your token set correctly. It should be in `$HOME/.config`. See https://github.com/edgarjs/alfred-github-repos/blob/master/lib/github/authorization.rb#L42

If the credentials file has your password, just delete it and login again.

**Comment by pakerchang** [comment]
Thank you for solving my problem.

The first time you open ``$HOME/.config`` Check the config, the token is fully recorded, but the problem of token not being used is still there.

After deleting the cache and trying to grab the repos again, it works fine!
