### ISSUE TITLE
Can't open a repository in the default browser

### ISSUE THREAD

**Issue by sparrovv** [edgarjs/alfred-github-repos#27]
Hi, I just found that workflow and looks like what I was looking for, but I think one of the last commits broke opening in a browser:

https://github.com/edgarjs/alfred-github-repos/commit/f708c450a641836fad308f8a01aa386a80a970b9#r43759373

**Comment by edgarjs** [comment]
Thanks for reporting. It was a naive change to copy the SSH url instead of the HTML url when you press `super+c` but the same url is used to open the repository in the browser.

It's been fixed in 2.1.4
