### ISSUE TITLE
Typo in .alfredworkflow file

### ISSUE THREAD

**Issue by vmitchell85** [edgarjs/alfred-github-repos#31]
I would've created a PR, but I don't think I can do that for the actual `.alfredworkflow` file.

There is a small typo in the keyword entry for `gh-token`, is says "Paste your **personall** access token" instead of "Paste your **personal** access token"

![image](https://user-images.githubusercontent.com/1248035/103693704-b6153100-4f67-11eb-969c-461bd2122181.png)

**Comment by edgarjs** [comment]
Thank you @vmitchell85
