### ISSUE TITLE
Typo in gh-login keyword input title

### ISSUE THREAD

**Issue by gkpotter** [edgarjs/alfred-github-repos#36]
There is a typo in the gh-login keyword input title ('personall' should be 'personal'). I don't actually see this text anywhere in the repo, but I did not build from source. I downloaded the latest release.

<img width="623" alt="Screen Shot 2021-06-14 at 12 36 24" src="https://user-images.githubusercontent.com/38485117/121927511-22f9d780-cd0d-11eb-8a6d-02935461c744.png">

**Comment by edgarjs** [comment]
Thanks for reporting. This has been fixed in https://github.com/edgarjs/alfred-github-repos/commit/6cd3924a6378ae0e06d93b4b334c29503d30a9bc but not yet released. Will bump a new version soon.

**Comment by gkpotter** [comment]
I see! Also, my bad for not checking the closed issues. 😅
