### ISSUE TITLE
[Bug] Small typo issue in gh-login

### ISSUE THREAD

**Issue by deerawan** [edgarjs/alfred-github-repos#38]
# Description
Version 3.1.2

# Issue
Small typo in description of `gh-login` command. It is supposed to be `personal`

![Image 2021-07-26 at 06 29 55](https://user-images.githubusercontent.com/85203411/126912633-f7ce24fd-eb1c-4111-8fc8-4a132e41c2d2.jpg)

**Comment by edgarjs** [comment]
Thanks for reporting. Just pushed new version with those fixes (3.1.3)
