### ISSUE TITLE
Modify to work with GitLab?

### ISSUE THREAD

**Issue by bwoodruff** [edgarjs/alfred-github-repos#39]
How difficulty would it be to modify this workflow to work with GitLab's API? For example, their query string to find a repo is:

`https://${GITLAB_HOST}/api/v4/projects?search=`

🙏🏻

**Comment by edgarjs** [comment]
@bwoodruff I haven't used Gitlab yet. But if it's the same REST API than GitHub, you can use the "Enterprise" feature to change the hostname of the API calls: https://github.com/edgarjs/alfred-github-repos#configuring-host-for-enterprise

Which internally it only sets the env var for the host in your Alfred workflow settings.
