### ISSUE TITLE
Stuck on "Fetching results"

### ISSUE THREAD

**Issue by firasm** [edgarjs/alfred-github-repos#40]
Hello there,

I wanted to file an issue with the `repo` command, it seems to get stuck on "fetching results".

My operating system is:

- macOS Big Sur 11.5.2
- Alfred Version 4.5.1 [1256]

I added my PAT with repo permissions. Screenshots below:

<img width="623" alt="Screen Shot 2021-08-30 at 12 27 32 PM" src="https://user-images.githubusercontent.com/2507459/131394043-3d426d74-9363-4fc8-b638-43f896eb2610.png">

Searching for the repo across all of GH seems to work okay.

<img width="623" alt="Screen Shot 2021-08-30 at 12 28 20 PM" src="https://user-images.githubusercontent.com/2507459/131394121-d6e0d941-b526-43c8-ac2c-f954a4c41004.png">

Let me know if there's any other information you need from me to troubleshoot this further.

**Comment by edgarjs** [comment]
Hi, did you authenticate with `gh-login <your-personal-access-token>`? If yes, you may need to generate a new access token with the `repo` permissions checked.

**Comment by firasm** [comment]
Ok I think I figured it out - it was working, just taking a really, really, really long time to query because I use GitHub Classroom for my 100+ student classes, and each org has several thousand repos. 

Once it pulled them all the first time, subsequent searches are much faster.

I need to remove myself as owner on all these repos! Thanks for a great workflow!

**Comment by edgarjs** [comment]
Oh I see. Thank you for the context. That's something happening to me as
well. And I'm trying to work on a solution for those cases.
