### ISSUE TITLE
Add open local file with cmd

### ISSUE THREAD

**Issue by AnKingMed** [edgarjs/alfred-github-repos#41]
I added 2 steps that make it so I can now open locally by holding cmd

1. Regex replace `^(.*[\\\/])` with ` ` 
2. Reveal in Finder with `~/Documents/GitHub/{query}`

I enjoy it and thought others might, so I figured I'd share

**Comment by edgarjs** [comment]
Hi @AnKingMed I think you created an issue instead of a PR.
