### ISSUE TITLE
Help by starting please...

### ISSUE THREAD

**Issue by MannyFay** [edgarjs/alfred-github-repos#56]
I want to use this workflow.. I'm very new to Alfred and this is my first try with workflows.

I've tried the steps at the beginning of the readme, but that didn't work.
Then I've read in internet, that I have to download the .alfredworkflow file, but I didn't found it :/

So what I have to do exactly?

**Comment by edgarjs** [comment]
You can read more about Alfred Workflows in their [help page](https://www.alfredapp.com/help/workflows/). And you can download this workflow in the [releases page](https://github.com/edgarjs/alfred-github-repos/releases) or in [Packal.org](https://www.packal.org/workflow/github-repos).

After installing it, then you can follow the instructions from the README.

Hope that helps.

**Comment by MannyFay** [comment]
Thanks @edgarjs :)
This was the the first Workflow I've added to Alfred - and the only one that has no link to the workflow file in the readme ;-P (or is it there and I didn't have seen it??)

But now it works properly! Very cool extension for Alfred. Thank you for providing that 👍
