### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by aronstrandberg** [edgarjs/alfred-github-repos#7]
This is great, but for me it only works for a small subset of my repos, since my school work is hosted on the university's Github Enterprise. Support to pull those repos too would be nice!

**Comment by cogell** [comment]
would love to see this as well!

**Comment by sveinnfannar** [comment]
I agree, would be fantastic

**Comment by nyetsche** [comment]
👍  this would be cool

**Comment by nyetsche** [comment]
It's possible it's as simple as changing this URL https://github.com/edgarjs/alfred-github-repos/blob/master/github#L13

But I haven't had a chance to test yet.

**Comment by edgarjs** [comment]
@nyetsche feel free to open a PR :)

**Comment by BenGitsCode** [comment]
Anyone confirmed that as working. This is my favorite of two github alfred workflows I use but I've never gotten either to work successfully with my company's enterprise domain 😭

**Comment by shazron** [comment]
For Github enterprise, add `/api/v3/` to the end of your corporate git url. So you would connect to `https://[GHE_HOST]/api/v3`.

**Comment by nyetsche** [comment]
I can confirm that @shazron 's minor URL change works!

**Comment by bskiefer** [comment]
Didn't work for me until I removed the `/` from `/api/v3/`. Just leaving this here in case anyone else has an issue.

**Comment by edgarjs** [comment]
A new version has been published, but I don't have an enterprise account to test with. Please let me know if it doesn't work.

You set the host with the `gh-host` action, for example: `gh-host https://example.com`. Note that it should not include any path at the end.
