### ISSUE TITLE
Private repos shows up duplicated

### ISSUE THREAD

**Issue by peterlauri** [edgarjs/alfred-github-repos#8]
Public repos shows up fine, only one per repo. However, the private repos are shown duplicates. See the below git-video. I have run *gh-update*, but it didn't help.

When I search on "ball" it shows duplicates (private repos), and searching for "python" it shows not duplicates (public records).

![alfred private repos duplicated](https://cloud.githubusercontent.com/assets/3514945/12521930/f30596de-c14d-11e5-8293-dcbc978fc645.gif)

**Comment by edgarjs** [comment]
Done in v1.1.0

**Comment by peterlauri** [comment]
Great, confirmed to be working!
